apps/inventario/urls.py
# inventario/urls.py
from django.urls import path
from . import views

app_name = 'inventario'  

urlpatterns = [

    path('', views.product_crud, name='product_crud'),
    
    path('registrarProducto/', views.registrarProducto, name='registrarProducto'),

    path('edicionProducto/<str:codigo>/', views.edicionProducto, name='edicionProducto'),

    path('editarProducto/', views.editarProducto, name='editarProducto'),

    path('eliminarProducto/<str:codigo>/', views.eliminarProducto, name='eliminarProducto'),

    path('cargar-inventario/', views.cargar_inventario, name='cargar_inventario'),

    path('buscar-producto/', views.listar_producto, name='buscarProducto'),




]

apps/login/urls.py
# login/urls.py
from django.urls import path, include
from . import views

app_name = 'login'


urlpatterns = [
    path('', views.home, name='home'), 
    path('logout/', views.exit, name='exit' )
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('apps.login.urls', namespace='login')),
    path('inventario/', include('apps.inventario.urls', namespace='inventario')),
    path('accounts/', include('django.contrib.auth.urls')),
]

apps/inventario/models.py
# inventario/models.py
from django.db import models
from django.contrib.auth.models import User

class Producto(models.Model):
    codigo = models.CharField(primary_key=True, max_length=6)
    nombre = models.CharField(max_length=50)
    cantidad = models.PositiveSmallIntegerField()
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre


class InventarioExcel(models.Model):
    codigo = models.CharField(max_length=500)
    nombre = models.CharField(max_length=500)
    marca = models.CharField(max_length=500)
    tipo_existencia = models.CharField(max_length=500)
    stock_actual = models.IntegerField()

    def __str__(self):
        return f'Código: {self.codigo}, Nombre: {self.nombre}'

apps/login/models.py
from django.db import models

# Create your models here.

apps/inventario/forms.py
from django import forms

class UploadFileForm(forms.Form):
    archivo_excel = forms.FileField(label='Seleccionar archivo Excel', help_text='Solo se permiten archivos en formato .xlsx y .xls')

apps/inventario/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Producto
from django.contrib import messages
from django.urls import reverse_lazy, reverse
from .forms import UploadFileForm
from .models import InventarioExcel
import pandas as pd
import numpy as np 
from django.http import JsonResponse

from django import forms
from .models import Producto
from django.http import JsonResponse




from django.contrib import messages


class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ['codigo', 'nombre', 'cantidad', 'usuario']


# Insertar Valores y Filrado


def listar_producto(request):
    nombre = request.GET.get('nombre')

    if nombre:
        productos_listados = InventarioExcel.objects.filter(nombre__icontains=nombre)
    else:
        productos_listados = InventarioExcel.objects.all()

    productos_json = list(productos_listados.values('codigo', 'nombre', 'marca', 'tipo_existencia', 'stock_actual'))
    return JsonResponse(productos_json, safe=False)


def registrarProducto(request):
    if request.method == 'POST':
        codigo = request.POST.get('codigo')
        nombre = request.POST.get('nombre')
        cantidad = request.POST.get('cantidad')
        usuario = request.user

        if not codigo or not nombre or not cantidad:
            return JsonResponse({'success': False, 'message': 'Por favor completa todos los campos.'})
        elif Producto.objects.filter(codigo=codigo).exists():
            return JsonResponse({'success': False, 'message': '¡El código ya está en uso!'})
        else:
            Producto.objects.create(
                codigo=codigo, nombre=nombre, cantidad=cantidad, usuario=usuario)
            return JsonResponse({'success': True, 'message': '¡Producto Registrado!'})
    else:
        form = ProductoForm()
        return render(request, "product_crud.html", {'form': form})




















## LOGIN DEL SISTEMA INVENTARIO

@login_required
def product_crud(request):
    productos_listados = Producto.objects.all()
    mensajes = messages.get_messages(request)
    return render(request, 'product_crud.html', {"Productos": productos_listados, "messages": mensajes})

def home(request):
    productos_listados = Producto.objects.all()
    messages.success(request, '¡PRODUCTO LISTADO!')
    return render(request, "product_crud.html", {"Productos": productos_listados})








# CRUD del SISTEMA INVENTARIO

def edicionProducto(request, codigo):
    producto = Producto.objects.get(codigo=codigo)
    return render(request, "product_edit.html", {"Producto": producto})

def editarProducto(request):
    if request.method == 'POST':
        codigo = request.POST['codigo']
        nombre = request.POST['nombre']
        cantidad = request.POST['cantidad']
        usuario = request.user  # Capturar el usuario autenticado

        producto = Producto.objects.get(codigo=codigo)
        producto.nombre = nombre
        producto.cantidad = cantidad
        producto.usuario = usuario  # Asignar el usuario autenticado al producto
        producto.save()

        messages.success(request, '¡Producto actualizado!')

        return redirect(reverse('inventario:product_crud'))

    return redirect(reverse('inventario:product_crud'))

def eliminarProducto(request, codigo):
    producto = Producto.objects.get(codigo=codigo)
    producto.delete()

    messages.success(request, '¡Producto eliminado!')

    return redirect(reverse('inventario:product_crud'))



## Carga de Arvhivos DEL SISTEM INVENTARIO
@login_required
def cargar_inventario(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            archivo_excel = request.FILES['archivo_excel']
            df = pd.read_excel(archivo_excel)

            # Rellenar valores faltantes con 0 para columnas numéricas
            df['Código'] = df['Código'].fillna(0)
            df['Stock Actual'] = df['Stock Actual'].fillna(0)

            # Rellenar valores faltantes con None para columnas de texto
            df['Nombre (Princip.)'] = df['Nombre (Princip.)'].fillna(np.nan)
            df['Marca'] = df['Marca'].fillna(np.nan)
            df['Tip. Existencia'] = df['Tip. Existencia'].fillna(np.nan)

            for index, row in df.iterrows():
                codigo = row['Código']
                nombre = row['Nombre (Princip.)']
                marca = row['Marca']
                tipo_existencia = row['Tip. Existencia']
                stock_actual = row['Stock Actual']
                InventarioExcel.objects.create(
                    codigo=codigo,
                    nombre=nombre,
                    marca=marca,
                    tipo_existencia=tipo_existencia,
                    stock_actual=stock_actual
                )
            messages.success(request, '¡Datos cargados desde Excel!')
            return redirect('inventario:cargar_inventario')
    else:
        form = UploadFileForm()
    return render(request, 'cargar_inventario.html', {'form': form})

apps/login/views.py
# login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.urls import reverse_lazy

# Create your views here.

@login_required
def home (request):
    return render(request, 'home.html')

@login_required
def products(request):
    return redirect(reverse_lazy('inventario:product_crud'))


@login_required
def cargarInventario(request):
    return redirect(reverse_lazy('inventario:cargar_inventario'))


def exit(request):
    logout(request)
    return redirect('home')

apps/inventario/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/app.css' %}">

</head>

<body>

    <div class="container py-4">
        {% block body %}

        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
        integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous">
    </script>

    <script src="{% static 'js/app.js' %}"></script>


    <script>
        var urlBuscarProducto = "{% url 'inventario:buscarProducto' %}";
    </script>

</body>

</html>

apps/inventario/templates/cargar_inventario.html
{% extends "./base.html" %}

{% block title %} Cargar Archivo {% endblock %}

{% block body %}
<div class="container mt-5">
    <h1 class="mb-4">Cargar Archivo Excel</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
            <label for="archivo_excel">Seleccionar archivo Excel</label>
            <input type="file" class="form-control" id="archivo_excel" name="archivo_excel" accept=".xlsx">
        </div>
        <button type="submit" class="btn btn-primary mt-3" disabled>Cargar</button>
    </form>
</div>
{% endblock %}

apps/inventario/templates/product_crud.html
{% extends "./base.html" %} {% block title %}Gestión de Productos{% endblock %}
{% block body %}
<div class="row">
    <div class="col-sm-12 col-md-6 col-lg-4 col-xl-4">
        {% if messages %} {% for message in messages %}
        <div class="alert alert-dismissible alert-success">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <strong class="text-dark">{{ message }}</strong>
        </div>
        {% endfor %} {% endif %}
        <h2>Gestión de Productos</h2>

        <div class="card">
            <div class="card-body">
                <form id="searchForm" method="GET">
                    <div class="form-group">
                        <input type="text" id="txtNombre" class="form-control" placeholder="Buscar por nombre"
                            maxlength="50" name="nombre" />
                    </div>
                    <button type="submit" class="btn btn-primary">Buscar</button>
                </form>
            </div>
        </div>
    </div>

    <div class="col-sm-12 col-md-6 col-lg-8 col-xl-8">
        <h1>Listado de Productos</h1>
        <div class="table-responsive py-2">
            <table class="table table-striped" id="tablaProductos">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Código</th>
                        <th>Nombre</th>
                        <th>Cantidad</th>
                        <th>Opciones</th>
                    </tr>
                </thead>
                <tbody id="productosBody">
                    <!-- Los resultados de búsqueda se mostrarán aquí -->
                </tbody>
            </table>
        </div>
    </div>
</div>

<!-- Botón para registrar producto -->
<button id="registrarProductoBtn" data-url="{% url 'inventario:registrarProducto' %}" style="display: none"></button>

<script>
    document.getElementById('registrarProductoBtn').addEventListener('click', function () {
        var url = this.getAttribute('data-url');
        var codigo = document.getElementById('codigo').value;
        var nombre = document.getElementById('nombre').value;
        var cantidad = document.getElementById('cantidad').value;

        fetch(url, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': '{{ csrf_token }}'
            },
            body: JSON.stringify({
                codigo: codigo,
                nombre: nombre,
                cantidad: cantidad
            })
        })
            .then(response => response.json())
            .then(data => {
                alert(data.message);
                if (data.success) {
                    window.location.href = '{% url 'inventario:product_crud' %}';
                }
            })
            .catch(error => {
                console.error('Error:', error);
            });
    });

    function agregarProducto(codigo, nombre, cantidad) {
        var url = document.getElementById('registrarProductoBtn').getAttribute('data-url');

        fetch(url, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': '{{ csrf_token }}'
            },
            body: JSON.stringify({
                codigo: codigo,
                nombre: nombre,
                cantidad: cantidad
            })
        })
            .then(response => response.json())
            .then(data => {
                alert(data.message);
                if (data.success) {
                    window.location.href = '{% url 'inventario:product_crud' %}';
                }
            })
            .catch(error => {
                console.error('Error:', error);
            });
    }




    function crearFilaProducto(producto, index) {
        var row = document.createElement('tr');
        row.innerHTML = '<td>' + (index + 1) + '</td>' +
            '<td>' + producto.codigo + '</td>' +
            '<td>' + producto.nombre + '</td>' +
            '<td>' + producto.stock_actual + '</td>' +
            '<td>' +
            '<input type="text" class="form-control" id="codigo_' + index + '" value="' + producto.codigo + '">' +
            '<input type="text" class="form-control" id="nombre_' + index + '" value="' + producto.nombre + '">' +
            '<input type="number" class="form-control" id="cantidad_' + index + '" value="1">' +
            '<button class="agregarProductoBtn btn btn-primary" data-index="' + index + '">Agregar Producto</button>' +
            '</td>';
        return row;
    }


    function manejarRespuesta(data) {
        var tbody = document.getElementById('productosBody');
        tbody.innerHTML = '';

        if (data && data.length > 0) {
            var fragment = document.createDocumentFragment();
            data.forEach(function (producto, index) {
                var row = crearFilaProducto(producto, index);
                fragment.appendChild(row);
            });
            tbody.appendChild(fragment);

            // Agregar evento de clic a los botones "Agregar Producto"
            var agregarBotones = document.querySelectorAll('.agregarProductoBtn');
            agregarBotones.forEach(function (btn) {
                btn.addEventListener('click', function () {
                    var index = this.getAttribute('data-index');
                    var codigo = document.getElementById('codigo_' + index).value;
                    var nombre = document.getElementById('nombre_' + index).value;
                    var cantidad = document.getElementById('cantidad_' + index).value;
                    agregarProducto(codigo, nombre, cantidad);
                });
            });
        } else {
            tbody.innerHTML = '<tr><td colspan="5">No se encontraron coincidencias.</td></tr>';
        }
    }


    document.addEventListener('click', function (event) {
        if (event.target.classList.contains('agregarProductoBtn')) {
            var codigo = event.target.getAttribute('data-codigo');
            var nombre = event.target.getAttribute('data-nombre');
            agregarProducto(codigo, nombre);
        }
    });

    document.getElementById('searchForm').addEventListener('submit', function (event) {
        event.preventDefault();

        var form = event.target;
        var nombre = form.querySelector('#txtNombre').value.trim();
        var url = '{% url 'inventario:buscarProducto' %}?nombre=' + encodeURIComponent(nombre);

        fetch(url)
            .then(response => response.json())
            .then(manejarRespuesta)
            .catch(error => {
                console.error('Error:', error);
            });
    });
</script>
{% endblock %}

apps/inventario/templates/product_edit.html
{% extends "./base.html" %}

{% block title %} Edición de Producto {% endblock %}

{% block body %}
<div class="row">
    <div class="col-md-4 offset-md-4">
        <h2>EDICIÓN DE PRODUCTO</h2>
        <div class="card">
            <div class="card-body">
                
                <form action="{% url 'inventario:editarProducto' %}" method="POST">{% csrf_token %}
                    <div class="form-group">
                        <input type="text" id="txtCodigo" name="codigo" value="{{ Producto.codigo }}" class="form-control" placeholder="Código"
                            minlength="6" maxlength="6" readonly required>
                    </div>
                    <div class="form-group">
                        <input type="text" id="txtNombre" name="descripcion" value="{{ Producto.descripcion }}" class="form-control" placeholder="Nombre"
                            maxlength="50" required>
                    </div>
                    <div class="form-group">
                        <input type="number" id="numCreditos" name="cantidad" value="{{ Producto.cantidad }}" class="form-control" min="1" max="9"
                            value="1" required>
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-success btn-block text-white">Guardar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

apps/login/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'css/app.css' %}">

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-info">
        <a class="navbar-brand" href="#">BHC</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href={%  url 'home' %}>Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href={% url 'inventario:product_crud' %}>Productos</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href={% url 'inventario:cargar_inventario' %}>Cargar Productos</a>
                </li>

                {% if request.user.is_authenticated  %}
                <li class="nav-item"> <a class="nav-link" href={% url 'exit' %}>Salir</a></li>
                {% else %}
                <li class="nav-item"> <a class="nav-link" href={% url 'login' %}>Ingresar</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="container py-4">
        {% block body %}

        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
        integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous">
    </script>

</body>

</html>

apps/login/templates/home.html
{% extends "base.html" %}

{% block title %} Gestión de inventario {% endblock %}

{% block body %}

<h1> Bienvenido  </h1>

{% endblock %}